### ISSUE TITLE
Stories glob is invalid

### ISSUE THREAD

**Issue by bodograumann** [storybookjs/vue-cli-plugin-storybook#104]
According to the [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs), the glob we are using to define the story files, is not valid.
I think this should be a simple change from `../../src/**/*.stories.(js|jsx|ts|tsx|mdx)` to `../../src/**/*.stories.@(js|jsx|ts|tsx|mdx)`, i.e. adding the `@` character.

**Comment by pksunkara** [comment]
This change is for storybook 6.0?

**Comment by bodograumann** [comment]
As I understood the migration guide, the glob is invalid regardless of the storybook version, but until now it worked by accident.

**Comment by pksunkara** [comment]
@shilman I am confused about this. Can you please explain what's happening?

**Comment by shilman** [comment]
@pksunkara As I understand it:
- the `.@(a|b|c)` syntax is actually the correct glob syntax
- the `.(a|b|c)` syntax worked accidentally in 5.3 because it's a valid regex, but is incorrect and caused problems with something we wanted to do in 6.0
- we want people using valid globs for future compatibility

Perhaps @yannbf or @ndelangen can clarify further?

**Comment by ndelangen** [comment]
That's 💯 accurate

**Comment by pksunkara** [comment]
What about pre 5.3? When was the @ syntax enabled?

**Comment by ndelangen** [comment]
@pksunkara we had to switch between minimatch/micromatch/nanomatch with various options to get it to work correctly.
This has been thrown around a bit in 6.0, so it's possible a glob that worked well in 5.3 was actually an invalid glob, which won't work in 6.0. And valid globs might not work in 5.3. That's all fairly unfortunate I know.

**Comment by pksunkara** [comment]
I understand that. But this plugin has different generators depending on the storybook versions. I want to know from what version of storybook is the `@` character supported so that I can make a fix for this issue.

**Comment by ndelangen** [comment]
There were a few iterations during 6.0.0 beta time, but main fix was added here:
https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md#600-beta18-may-29-2020
