### ISSUE TITLE
CB() never called! (taobao mirror issue)

### ISSUE THREAD

**Issue by RCVarley** [storybookjs/vue-cli-plugin-storybook#107]
### The Problem
As reported in https://github.com/npm/cli/issues/1737, when creating a new project and adding storybook to it with:

```
vue create project-name
cd project-name
vue add storybook
```

I got this error:
```
9686 http fetch GET 200 https://cdn.npm.taobao.org/polished/-/polished-3.6.5.tgz 335209ms
9687 silly extract polished@^3.4.4 extracted to C:\Users\[user]\code\project-name\node_modules\.staging\polished-d941e2b9 (335211ms)
9688 timing npm Completed in 389597ms
9689 error cb() never called!
```

This error was generated while attempting to use NPM. I also tried Yarn and it failed to fetch `polished-3.6.5.tgz`; I wonder if this was happening in the background...

### The Solution
The issue was related to the taobao mirror of the NPM registry.

You can change the registry to use with `vue create project-name -r https://registry.npmjs.org`.

There is also a setting in `.vuerc` that you can change (`"useTaobaoRegistry": false,`).

### Further Reading:
https://docs.npmjs.com/using-npm/registry.html
https://cli.vuejs.org/guide/creating-a-project.html#vue-create
https://medium.com/vuetify/productivity-in-vue-part-2-1dc209062cae

**Comment by pksunkara** [comment]
This is actually `@vue/cli` issue.
