### ISSUE TITLE
Storybook 6 support by default

### ISSUE THREAD

**Issue by steveworkman** [storybookjs/vue-cli-plugin-storybook#108]
👋  A snag list for things that I noticed when setting the required version to `^6.0.0` when invoking the plugin. I'll do my best to submit PRs for all of these

- [x] The glob is now incorrect. It should have an `@` before the `(js|jsx....)`
- [x] Instead of installing all the dependencies, it can use the `@storybook/essentials` package
- [x] This will enable the `main.js` file to be simpler, and it won't need the Vue/JSX hack
- [x] The default stories should use `<canvas>` instead of `<preview>`
- [x] Add documentation to `MyButton.vue` so that it can show off auto-documentation in `<ArgsTable>`

**Comment by pksunkara** [comment]
I fixed the glob after some testing
