### ISSUE TITLE
I have error "Definition for rule 'import/no-unresolved' was not found"

### ISSUE THREAD

**Issue by OmelyanenkoV** [storybookjs/vue-cli-plugin-storybook#121]
i generated a new project using vue cli
when adding ```vue add storybook``` files are generated
and getting error when ```yarn storybook: serve```
i don't know why this happens, it's a clear project
![image](https://user-images.githubusercontent.com/47278133/143889343-1f255d09-ce92-4984-9823-09f38efaffba.png)

package.json
![image](https://user-images.githubusercontent.com/47278133/143889526-fdf2ec47-7631-4871-828f-f67ba5a13482.png)

**Comment by bodograumann** [comment]
What is `generated-stories-entry.js`?
I don’t think this is provided by this package.

**Comment by OmelyanenkoV** [comment]
> What is `generated-stories-entry.js`?
> I don’t think this is provided by this package.

Don't know, this is a clean project ```vue create test``` and ```vue add storybook```. that's all

**Comment by OmelyanenkoV** [comment]
I am trying again now. and I get the same error

**Comment by bodograumann** [comment]
Is there a reason you are using vue-2? For new projects I would always recommend vue-3.
When using vue-3 you can also choose storybook ^6.4.1.
I can’t recreate you setup right now, because I’m already on vue-cli-5, but maybe you can share you minimal setup as a github repo?

**Comment by OmelyanenkoV** [comment]
https://github.com/OmelyanenkoV/vue_storybook

**Comment by bodograumann** [comment]
Seems like the eslint version is too old. But imho this internal storybook file should not be linted in the first place. Do you know why it is linted @pksunkara ?

**Comment by pksunkara** [comment]
It's nothing this repo does. I think the fix here is to ignore that file in gitignore (or eslintignore) because it seems to be generated by storybook.
