### ISSUE TITLE
Add storybook-static to gitignore?

### ISSUE THREAD

**Issue by lazarljubenovic** [storybookjs/vue-cli-plugin-storybook#19]
Not sure what's the common and recommended way of doing things in the Vue CLI plugin, but seeing how it changes my files to set everything up for me, it seems like this would be a nice addition as well. It could add `storybook-static` to `.gitignore`, for example right below `/dist` (if it exists), or at the end of the file.

It's a built artifact just like the `dist/` folder so I assume everyone would want it hidden.

**Comment by pksunkara** [comment]
Would welcome a PR.
