### ISSUE TITLE
StorySource addon doesn't work

### ISSUE THREAD

**Issue by tonimc** [storybookjs/vue-cli-plugin-storybook#33]
The StorySource addon doesn't work, I add it to the project add the source code of the story is doesn't show.
Steps to reproduce it:
1. Create Vue project
2. Add storybook using this plugins
3. Add StorySouce to `package.json`:
`"@storybook/addon-storysource": "^4.0.0-alpha.20",`
4. Install dependencies:
`$ yarn/npm install`
5. Register addon in the addons config file `storybook/config/addons.js`:
`import '@storybook/addon-storysource/register'`
6. Run storybook:
`npm/yarn run serve:storybook`
7.Storybook is loaded and addon appear in the addons panel, but the source code is empty as you can see in the screenshot.
![image](https://user-images.githubusercontent.com/750002/46550687-1115d480-c8d6-11e8-9a98-6596c75e6c78.png)

**Comment by tonimc** [comment]
@pksunkara any update about this?

**Comment by pksunkara** [comment]
Definitely on the list, unfortunately, I need to upgrade storybook version first. Taking a bit of time. 😞

**Comment by backbone87** [comment]
see https://github.com/storybooks/storybook/tree/master/addons/storysource#getting-started

you are missing the webpack rule, to actually parse the source of the story.

`vue.config.js`:
```js
module.exports = {
  chainWebpack: (config) => {
    config.module
      .rule('storysource')
      .test(/\.stories\.tsx?$/)
      .pre()
      .use('storysource')
      .loader(require.resolve('@storybook/addon-storysource/loader'))
      .options({ parser: 'typescript' });
  },
};
```

idk, if we want to integrate this into the plugin and check for the existance of the storysource addon.

**Comment by vip30** [comment]
For preventing #79 error,

We need to add `before('vue')` in the chain webpack

```
module.exports = {
  chainWebpack: (config) => {
    config.module
      .rule('storysource')
      .test(/\.stories\.tsx?$/)
      .pre()
      .before('vue') // same as unshift
      .use('storysource')
      .loader(require.resolve('@storybook/addon-storysource/loader'))
      .options({ parser: 'typescript' });
  },
};
```

**Comment by pksunkara** [comment]
This should work simply now since it is now an addon and Storybook 5.3 is released. https://github.com/storybookjs/storybook/tree/v5.3.3/addons/storysource#install-using-preset

You don't need any special config for this.
