### ISSUE TITLE
Storybook don't build

### ISSUE THREAD

**Issue by omarcresp** [storybookjs/vue-cli-plugin-storybook#59]
config/storybook/config.js
```
/* eslint-disable import/no-extraneous-dependencies */
import { configure } from '@storybook/vue';

const req = require.context('../../src/stories', true, /.stories.js$/);

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```
src/stories/index.stories.js
```
/* eslint-disable import/no-extraneous-dependencies */
import { storiesOf } from '@storybook/vue';

import HomeView from '../views/Home.vue';

storiesOf('Home view', module)
  .add(
    'Simple rendering view',
    () => ({
      components: { HomeView },
      template: '<home-view />',
    }),
    {
      notes: 'Documentación acerca de que es esta vista.',
    },
  );
```

storybook:serve works whitout problems but storybook:build don't work. It compile but the `iframe.html` only show a message
```
No Preview
Sorry, but you either have no stories or none are selected somehow.

Please check the Storybook config.
Try reloading the page.
If the problem persists, check the browser console, or the terminal you've run Storybook from.
```
I don't have errors on build time
I don't have errors in browser console

**Comment by pksunkara** [comment]
This is with the latest version?

**Comment by omarcresp** [comment]
Yes

**Comment by AstiV** [comment]
I am facing a similar issue using storybook/html. I am following the manual setup guide and while using the following example in `config.js` works fine:
`import { configure } from '@storybook/html';

function loadStories() {
  require('../stories/index.js');
  // You can require as many stories as you need.
}

configure(loadStories, module);`

The next example does throw the above mentioned error in the browser.
`import { configure } from '@storybook/html';

function loadStories() {
  const req = require.context('../stories', true, /\.stories\.js$/);
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);`

**Comment by AstiV** [comment]
Update: Just found my mistake...
The regex in the second example: `/\.stories\.js$/` does not work for the file named `index.js`... 
but the file should be named `index.stories.js`.

Maybe a line about this in the documentation would help other beginners prevent the issue.

**Comment by pksunkara** [comment]
I am closing this because there's no new info and all the tests are working.
