### ISSUE TITLE
How to know when custom webpack config is invoked from storybook:serve/build?

### ISSUE THREAD

**Issue by noelheesen** [storybookjs/vue-cli-plugin-storybook#65]
Hello,

In the option `chainWebpack` in `vue.config.js` I have certain plugins I only want to include when running storybook. How can I know it's the storybook serve/build command?

I have modified the tasks in node_modules to add `process.env.VUE_CLI_STORYBOOK = 'serve' || 'build'` which I can read from the chainWebpack fn.

Would you consider adding an env var which indicates the storybook process is running?

**Comment by pksunkara** [comment]
I would welcome a PR.
