### ISSUE TITLE
Using the latest version 5.1.9 of Storybook

### ISSUE THREAD

**Issue by fernandoagarcia** [storybookjs/vue-cli-plugin-storybook#70]
Is it possible to use a specific version of Storybook?  I am trying some addons that are only working on the latest 5.1.9 because of some core-js dependency. I've testing the direct install and the addons work fine. However using this plugin it seems to fail on serve.

**Comment by pksunkara** [comment]
You have to be more clear. I don't understand your setup from your message. I am currently using storybook 5.1.9 with this plugin and it's working for me.

**Comment by fernandoagarcia** [comment]
@pksunkara thanks for the reply. I'm using vue-cli-plugin-storybook 0.6.1 and you are correct it is using Storybook 5.1.9.

The issue I'm having is when I use the addon '@storybook/addon-viewport' Storybook fails with: 
`Module not found: Error: Can't resolve 'core-js/modules/es.array.concat' in`

**Comment by pksunkara** [comment]
Ideally it should not be an issue. But what this plugin does is that it uses your vue project webpack config as a starter. You need to upgrade your vue-cli deps to 4.0.0-alpha.4 which has core-js stuff.

**Comment by fernandoagarcia** [comment]
@pksunkara just updated on all of my packages with code-js ^3.1.2 and I am now using 4.0.0-alpha.4

but still getting the same error: 

`Module not found: Error: Can't resolve 'core-js/modules/es.array.concat' in '/Users/fernandogarcia/git/fox/webpack/node_modules/@storybook/addon-viewport/dist'`

Found an issue posted on : [`Storybook's Gihub`](https://github.com/storybookjs/storybook/issues/7090) that says it is related to 5.1.9 but if you have the addon working then it is probably my setup.

**Comment by fernandoagarcia** [comment]
@pksunkara So a quick correction. I keep getting 5.0.11 installed which is why the addon was failing. I tried re-invoking the generator for this vue cli plugin and I can't seem to get 5.1.9 installed.

`
Storybook 5.0.11 started                         │
│   9.46 s for manager and 10 s for preview          │
│                                                    │
│   Local:            http://localhost:6006/         │
│   On your network:  http://10.0.10.79:6006/        │
│                                                    │
│   A new version (5.1.9) is available!              │
│                                                    │
│   Read full changelog here: https://git.io/fhFYe  
`

**Comment by pksunkara** [comment]
Check your yarn.lock or package-lock.json. Also make sure you have storybook@5.1.9 in your package.json

**Comment by fernandoagarcia** [comment]
@pksunkara  I deleted my yarn.lock but also had to run `vue add vue-cli-plugin-storybook` again so it would install the deps. Now it is working @5.1.9 with all the addons. Thank you for your help.
