### ISSUE TITLE
Support for Component Story Format (CSF)

### ISSUE THREAD

**Issue by iliawnek** [storybookjs/vue-cli-plugin-storybook#74]
Does this plugin support Storybook's [Component Story Format](https://storybook.js.org/docs/formats/component-story-format/)? I can't seem to get it working, even with a minimal project setup.

```
$ ./node_modules/@storybook/vue/bin/index.js --version
5.2.4
```

**Comment by LeBenLeBen** [comment]
It works for me. What exactly is not working for you? Can you share some errors?

**Comment by iliawnek** [comment]
```
$ nvm current
v12.4.0
```

1. `vue create vue-storybook-csf-test` → Babel
2. `vue add storybook` → Initial framework
3. Add `csf.stories.js` which defines a story using CSF.
4. `yarn storybook:serve`

Following these steps, I cannot see the CSF story on Storybook (only the example stories defined using `storiesOf`).

Here's a test repo: https://github.com/iliawnek/vue-storybook-csf-test

**Comment by LeBenLeBen** [comment]
There's an issue with you configuration file here: https://github.com/iliawnek/vue-storybook-csf-test/blob/master/config/storybook/config.js#L4-L10

With Storybook 5.2, it must be adapted to just:

```
import { configure } from '@storybook/vue'

configure(require.context('../../src/stories', true, /\.stories\.js$/), module)
```

See https://storybook.js.org/docs/basics/writing-stories/#loading-stories for details.

**Comment by iliawnek** [comment]
That's it working now, thanks for your help!
