### ISSUE TITLE
MyButton.vue styles should be scoped

### ISSUE THREAD

**Issue by nickeyvee** [storybookjs/vue-cli-plugin-storybook#82]
Really just a minor inconvenience, but I encountered an issue where the styles from `MyButton.vue` where leaking into my other components.

### `MyButton.vue`
![image](https://user-images.githubusercontent.com/20284107/71368341-b2d61f80-2575-11ea-87ba-321d6b4d7d13.png)

**Comment by pksunkara** [comment]
Would welcome a PR since it's very minor.
