### ISSUE TITLE
Migration should install @storybook/vue

### ISSUE THREAD

**Issue by bodograumann** [storybookjs/vue-cli-plugin-storybook#90]
In commit https://github.com/storybookjs/vue-cli-plugin-storybook/commit/fd843e16f202317debd658de42bdd61c9ab747d5 you changed `@storybook/vue` to a peer dependency.
I just ran `vue upgrade` to update the vue plugins and after that found out that `@storybook/vue` is not installed anymore. You should install it during the `vue upgrade` process, if it is not already installed.

**Comment by pksunkara** [comment]
Hmm.. I should have. But it is also the reason I bumped version to 1

**Comment by pksunkara** [comment]
I am closing this as out of date. @bodograumann Unless you want to add a migrator?

**Comment by bodograumann** [comment]
Agreed. Don’t think it is worth the effort anymore.
