### ISSUE TITLE
Allow --docs flag in build script

### ISSUE THREAD

**Issue by LeBenLeBen** [storybookjs/vue-cli-plugin-storybook#91]
Storybook accepts a `--docs` flag in its native build script to build only the `docs` views and not the canvas. It would be great that this plugin allow to pass this flag and forward it to Storybook.

Reference: https://github.com/storybookjs/storybook/blob/d1196f73767caaa724a6984ef7409748e0329075/lib/core/src/server/cli/prod.js#L23

**Comment by pksunkara** [comment]
PRs are welcome, it should be a very easy fix
