### ISSUE TITLE
How to get translations within <i18n> blocks to work?

### ISSUE THREAD

**Issue by dnasir** [storybookjs/vue-cli-plugin-storybook#96]
As the title suggests, I have my localisation texts located inside the components they are associated with. For example;

```vue
<i18n>
{
    "en": {
        "tripIdFilter": {
            "inputLabel": "Trip IDs"
        }
    },
    "nb": {
        "tripIdFilter": {
            "inputLabel": "Tur IDer"
        }
    }
}
</i18n>
```

When I load up Storybook, the translations don't show up. Instead I just get the key for the translation.

This works fine in the app.

**Comment by pksunkara** [comment]
Are you sure this is not an issue in Storybook?

**Comment by dnasir** [comment]
You're right. I assumed it was a compilation time thing, which is why I posted the issue here. The solution has been posted here: https://github.com/dlucian/vuejs-storybook-i18n/issues/1#issuecomment-587607439
